pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git poll: true, branch: 'jenkinsFriendly', url: 'https://github.com/Uncle-Jules/Nordic-Motorhome-Eksamen.git'

                // Run Maven on a Unix agent.
                sh "mvn install -DskipTests clean package"

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }

        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
        stage('Deploy'){
            steps{
                'sh #!/bin/bash
                 FILE=NMP-1.0.0.pid
                 if [ -f "$FILE" ];
                 then
                 read pid < "$FILE"
                 kill "$pid"
                 rm "$FILE"
                 fi'
            }
            post{
                success {
                    'sh nohup java -jar demo-0.0.1-SNAPSHOT.jar &
                     echo $! >> demo-0.0.1-SNAPSHOT.pid
                     sleep 1'
                }
            }
        }
    }
}
